- name: Install Nginx
  hosts: cores
  tasks:
  - name: Install gnupg
    ansible.builtin.apt:
      name: gnupg
      state: present
      update_cache: true
    become: true
  - name: Install curl
    ansible.builtin.apt:
      name: curl
      state: present
      update_cache: false
    become: true
  - name: Install public key for package management system
    ansible.builtin.shell:  |
      curl --output /usr/share/keyrings/nginx-keyring.gpg https://unit.nginx.org/keys/nginx-keyring.gpg
    args: 
      creates: /usr/share/keyrings/nginx-keyring.gpg
    become: true
  - name: Create package source list file
    ansible.builtin.shell:  |
      echo "deb [signed-by=/usr/share/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ lunar unit"  > /etc/apt/sources.list.d/unit.list
      echo "deb-src [signed-by=/usr/share/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ lunar unit"  >> /etc/apt/sources.list.d/unit.list
    args: 
      creates: /etc/apt/sources.list.d/unit.list
    become: true
  - name: Install Nginx Unit
    ansible.builtin.apt:
      name: unit
      state: present
      update_cache: true
    become: true
  - name: Install Nginx Unit Python
    ansible.builtin.apt:
      name: unit-python3.11
      state: present
      update_cache: false
    become: true
  - name: Restart Nginx Unit
    ansible.builtin.service:
      name: unit
      enabled: yes
      state: restarted
      daemon_reload: true
    async: 60
    poll: 5
    become: true
  - name: Create /web/www directory
    ansible.builtin.file:
      path: /web/www
      state: directory
      owner: unit
      group: unit
      mode: 0750
    become: true
  - name: Install Python VENV
    ansible.builtin.shell:  |
      /usr/bin/python3.11 -m venv /web/venv
      . /web/venv/bin/activate
      /web/venv/bin/pip install Flask
      deactivate
    args: 
      creates: /web/venv/
    become: true
  - name: Update web application directory ownership
    ansible.builtin.file:
      path: /web/
      state: directory
      owner: unit
      group: unit
      follow: false
      recurse: true
    become: true
  